# Generated by Django 3.2.12 on 2022-04-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220422_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
