# Generated by Django 3.2.12 on 2022-04-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220422_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': '回覆', 'verbose_name_plural': '回覆'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
